python run.py \
    --task_name twi \
    --data_dir training_data/weibo/catar/width \
    --overwrite_output_dir \
    --do_eval \
    --do_train \
    --evaluate_during_training \
    --model_name_or_path ./xlm-model \
    --cache_dir ./xlm-model \
    --num_train_epochs 20 \
    --eval_steps 10 \
    --per_device_eval_batch_size 16 \
    --per_device_train_batch_size 16 \
    --learning_rate 1e-5 \
    --output_dir result/weibo_catar_width \
    --seed 103 \
    --template "*cls**sent_0*for_this_*mask*_story.*sep+*" \
    --cl_nn_size 64 \
    --alp 0.5 \
    --noise_norm 1.5 \
    --grad_loss \
    --position_dataset \
    --position \
    --pooling_sent_limit 128
